# .github/workflows/firebase-hosting-merge.yml
name: Deploy to Firebase Hosting on merge
on:
    push:
        branches: [main]

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest

        # These envs are available to the build (Next.js will inline NEXT_PUBLIC_*)
        env:
            NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
            NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
            NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
            NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
            NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
            NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}
            NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}
            NEXT_PUBLIC_GOOGLE_MAP_ID: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAP_ID }}
            GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
            GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
            # NEXT_TELEMETRY_DISABLED: 1

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'npm'

            - run: npm ci
            - run: npm run build

            # Authenticate to GCP using the same SA JSON you use for Firebase
            - name: Auth to Google Cloud
              uses: google-github-actions/auth@v2
              with:
                  credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_AI_TRIP_PLANNER_2241E }}

            - name: Setup gcloud
              uses: google-github-actions/setup-gcloud@v2

            # Idempotent; safe to run every time. If your SA can't enable services,
            # enable them once in the console instead.
            - name: Enable required APIs
              run: |
                  gcloud config set project ai-trip-planner-2241e
                  gcloud services enable \
                    cloudfunctions.googleapis.com \
                    run.googleapis.com \
                    cloudbuild.googleapis.com \
                    artifactregistry.googleapis.com \
                    secretmanager.googleapis.com

            - name: Deploy to Firebase Hosting
              uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: ${{ secrets.GITHUB_TOKEN }}
                  firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_AI_TRIP_PLANNER_2241E }}
                  channelId: live
                  projectId: ai-trip-planner-2241e
              env:
                  FIREBASE_CLI_EXPERIMENTS: webframeworks
